server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true 
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.cimknwts3ktb.ap-northeast-2.rds.amazonaws.com:3306/macburger?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: 1q2w3e4r
   
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
          
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 748510625033-ld6t1ofmvvtvrob0o5dfbvf9d5uq4tc1.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
    
mybatis:
  mapper-locations:
  - /mappers/*.xml

file:
  path: C:/junhyeong/junburger\burger-backend/upload
  downloadPath:  C:/junhyeong/junburger\burger-backend/download
  
